typography_spectrum: 0.8721280989702791
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.19664683495648205
  lightness: 0.4461622459348291
  saturation: 0.5854496664833277
  rhythmicContrast: 0.037966264644637704
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.06943735247477889
analytics:
  google: null
  facebook: null
  twitter: null
name: danielbeattie
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Daniel Beattie
purpose: []
